name: CI-CD
run-name: Build, Test, Deploy
on:
  - push
  - workflow_dispatch # Permit manual initiation
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm ci
      - run: npm run build
      
      - run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2

  deploy:
    # Wait for tests to complete
    needs: tests 
    # Only publish if tagged v*
    if: startsWith(github.event.ref, 'refs/tags/v')    
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: build # Path
          token: ${{ secrets.NPM_TOKEN }}
